### PR TITLE
Straight-line optimizations (messy)

### PR DESCRIPTION
**Pull request by lukego**
This branch contains work-in-progress optimizations.

The effect on `interlaken.snabb.co` is to increase performance from ~2.0 Mpps to ~4.2 Mpps. I hope the effect will be similar on grindelwald.

These changes mostly tweak LuaJIT behaviour to avoid interpreted mode and garbage collection. Some are sane, some are mysterious, some are oversimplified, but all are effective in my measurements.

@n-nikolaev and @dpino please let me know how this works for you!

### CODE REVIEW

**Comment by lukego** [comment]
Great analysis! I would be really happy to hand-over these hacks to you and let you implement a proper solution, if that suits you?

Sorry too: I believe we are clashing with the 05 NIC on grindelwald. I used that for some tests now too. I suspect your results are tainted by a loadgen that I was running. (The results here are faster than the theoretical maximum for 256-bytes on 10GbE of ~ 4.45 Mpps.) I will stop using the 05 NIC now :-).

**Comment by lukego** [comment]
(To elaborate on "tainting": I was alternating between 256 and 64 byte packets and each has different expected performance.)

FYI my workflow now is:
1. Start loadgen in the background.
2. Start VM in the background.
3. Run snabbnfv-bench directly to take a measurement.

I can repeat the last step to take a reasonably accurate new measurement in ~ 5 seconds. Great turn-around time on testing. (Fantastic that reconnect-to-VM works so robustly now; this is also thanks to the straightline branch - and to Nikolay :))

**Comment by dpino** [comment]
OK, sounds good. I will look more in detail to each of these patches.

**Comment by ghost** [comment]
What is the current status of these patches? I see DRAFT and TEMPORARY labels. Should we consider them for merging on the branch or after straightline becomes master?

**Comment by dpino** [comment]
@n-nikolaev I'm working on them. Unfortunately didn't have much time last week. I would not merge them for the moment.

**Pull request closed without merging**
